Attempt #3 at optimization: increasing Epochs

Results: 
Original = Loss of .5553 and Accuracy of .7265 
Trial #1 adding more hidden layers = Loss of .5517 and Accuracy of .7266 
Trial #2 = Loss of .5566 and Accuracy of .7272
Trial #3 = Loss of .5573 and Accuracy of .7231

Increasing the Number of Epochs did not improve the accuracy, in fact it hurt the accuracy.

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split as TTS
from sklearn.preprocessing import StandardScaler as SS
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
df = pd.read_csv("charity_data.csv")
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df = df.drop(['EIN', 'NAME'], axis =1)

df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_cnt = df.value_counts(df['APPLICATION_TYPE'])
app_type_cnt

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_cnt[app_type_cnt<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    df['APPLICATION_TYPE'] = df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_type_cnt = df.value_counts(df['CLASSIFICATION'])
class_type_cnt

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2190        1
C2380        1
C2500        1
C2561        1
C8210        1
Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_type_cnt = class_type_cnt[class_type_cnt > 1]
class_type_cnt

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1278       10
C1238       10
C1235        9
C1237        9
C7210        7
C1720        6
C4100        6
C2400        6
C1600        5
C1257        5
C2710        3
C1260        3
C0           3
C1267        2
C1246        2
C1256        2
C3200        2
C1234        2
dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_type_cnt[class_type_cnt<800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    df['CLASSIFICATION'] = df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2235
C3000     1918
C2100     1883
C3700        1
C2380        1
C1900        1
C1248        1
C1732        1
C4500        1
C4200        1
C2570        1
C1580        1
C2600        1
C4120        1
C2561        1
C8210        1
C2190        1
C2500        1
C1236        1
C1370        1
C1283        1
C1728        1
C2170        1
C5200        1
C2150        1
C1245        1
C6100        1
C1570        1
C1820        1
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
df_dummy = pd.get_dummies(df)
df_dummy

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
df_target = df_dummy['IS_SUCCESSFUL'].values

df_feat = df_dummy.drop(['IS_SUCCESSFUL'], axis = 1).values

In [11]:
# Split the preprocessed data into a training and testing dataset

xtrain, xtest, ytrain, ytest = TTS(df_feat, df_target, random_state = 78)

In [12]:
# Create a StandardScaler instances
scaler = SS()

# Fit the StandardScaler
X_scaler = scaler.fit(xtrain)

# Scale the data
xtrain_scaled = X_scaler.transform(xtrain)
xtest_scaled = X_scaler.transform(xtest)

In [13]:
# Create a method that creates a new Sequential model with hyperparameter options
num_features = len(xtrain)
hidden_nodes_1 = 8
hidden_nodes_2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense
       (units=hidden_nodes_1,
        input_shape = (69,),
        input_dim= num_features, 
        activation = "relu"
       ))

# Second hidden layer
nn.add(tf.keras.layers.Dense
      (units = hidden_nodes_2, 
       activation = "relu"
      ))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

#Check the structure
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 560

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 611
Trainable params: 611
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

In [15]:
print(xtrain_scaled.shape)
print(ytrain.shape)

(25724, 69)
(25724,)

In [16]:
# Train the model
fit_model = nn.fit(xtrain_scaled, ytrain, epochs = 200)

Epoch 1/200
804/804 [==============================] - 1s 848us/step - loss: 0.6368 - accuracy: 0.6872
Epoch 2/200
804/804 [==============================] - 1s 838us/step - loss: 0.5898 - accuracy: 0.7263
Epoch 3/200
804/804 [==============================] - 1s 636us/step - loss: 0.5764 - accuracy: 0.7284
Epoch 4/200
804/804 [==============================] - 1s 630us/step - loss: 0.5711 - accuracy: 0.7296
Epoch 5/200
804/804 [==============================] - 1s 626us/step - loss: 0.5684 - accuracy: 0.7295
Epoch 6/200
804/804 [==============================] - 1s 679us/step - loss: 0.5663 - accuracy: 0.7301
Epoch 7/200
804/804 [==============================] - 1s 707us/step - loss: 0.5644 - accuracy: 0.7308
Epoch 8/200
804/804 [==============================] - 1s 697us/step - loss: 0.5608 - accuracy: 0.7297
Epoch 9/200
804/804 [==============================] - 1s 698us/step - loss: 0.5589 - accuracy: 0.7302
Epoch 10/200
804/804 [==============================] - 1s 750us/step - loss: 0.5570 - accuracy: 0.7315
Epoch 11/200
804/804 [==============================] - 1s 717us/step - loss: 0.5561 - accuracy: 0.7314
Epoch 12/200
804/804 [==============================] - 1s 699us/step - loss: 0.5551 - accuracy: 0.7309
Epoch 13/200
804/804 [==============================] - 1s 713us/step - loss: 0.5548 - accuracy: 0.7310
Epoch 14/200
804/804 [==============================] - 1s 702us/step - loss: 0.5537 - accuracy: 0.7320
Epoch 15/200
804/804 [==============================] - 1s 733us/step - loss: 0.5533 - accuracy: 0.7322
Epoch 16/200
804/804 [==============================] - 1s 691us/step - loss: 0.5529 - accuracy: 0.7324
Epoch 17/200
804/804 [==============================] - 1s 692us/step - loss: 0.5525 - accuracy: 0.7320
Epoch 18/200
804/804 [==============================] - 1s 693us/step - loss: 0.5524 - accuracy: 0.7326
Epoch 19/200
804/804 [==============================] - 1s 708us/step - loss: 0.5522 - accuracy: 0.7327
Epoch 20/200
804/804 [==============================] - 1s 626us/step - loss: 0.5518 - accuracy: 0.7313
Epoch 21/200
804/804 [==============================] - 1s 637us/step - loss: 0.5520 - accuracy: 0.7327
Epoch 22/200
804/804 [==============================] - 1s 626us/step - loss: 0.5513 - accuracy: 0.7319
Epoch 23/200
804/804 [==============================] - 1s 628us/step - loss: 0.5512 - accuracy: 0.7324
Epoch 24/200
804/804 [==============================] - 1s 691us/step - loss: 0.5511 - accuracy: 0.7329
Epoch 25/200
804/804 [==============================] - 1s 715us/step - loss: 0.5510 - accuracy: 0.7322
Epoch 26/200
804/804 [==============================] - 1s 741us/step - loss: 0.5505 - accuracy: 0.7324
Epoch 27/200
804/804 [==============================] - 1s 736us/step - loss: 0.5506 - accuracy: 0.7328
Epoch 28/200
804/804 [==============================] - 1s 747us/step - loss: 0.5502 - accuracy: 0.7330
Epoch 29/200
804/804 [==============================] - 1s 823us/step - loss: 0.5500 - accuracy: 0.7327
Epoch 30/200
804/804 [==============================] - 1s 813us/step - loss: 0.5501 - accuracy: 0.7329
Epoch 31/200
804/804 [==============================] - 1s 764us/step - loss: 0.5497 - accuracy: 0.7334
Epoch 32/200
804/804 [==============================] - 1s 726us/step - loss: 0.5497 - accuracy: 0.7344
Epoch 33/200
804/804 [==============================] - 1s 759us/step - loss: 0.5497 - accuracy: 0.7336
Epoch 34/200
804/804 [==============================] - 1s 744us/step - loss: 0.5498 - accuracy: 0.7325
Epoch 35/200
804/804 [==============================] - 1s 662us/step - loss: 0.5493 - accuracy: 0.7343
Epoch 36/200
804/804 [==============================] - 1s 705us/step - loss: 0.5492 - accuracy: 0.7328
Epoch 37/200
804/804 [==============================] - 1s 668us/step - loss: 0.5491 - accuracy: 0.7325
Epoch 38/200
804/804 [==============================] - 1s 684us/step - loss: 0.5488 - accuracy: 0.7328
Epoch 39/200
804/804 [==============================] - 1s 630us/step - loss: 0.5488 - accuracy: 0.7340
Epoch 40/200
804/804 [==============================] - 1s 696us/step - loss: 0.5487 - accuracy: 0.7336
Epoch 41/200
804/804 [==============================] - 1s 702us/step - loss: 0.5486 - accuracy: 0.7341
Epoch 42/200
804/804 [==============================] - 1s 694us/step - loss: 0.5485 - accuracy: 0.7324
Epoch 43/200
804/804 [==============================] - 1s 689us/step - loss: 0.5481 - accuracy: 0.7336
Epoch 44/200
804/804 [==============================] - 0s 620us/step - loss: 0.5483 - accuracy: 0.7341
Epoch 45/200
804/804 [==============================] - 1s 625us/step - loss: 0.5479 - accuracy: 0.7332
Epoch 46/200
804/804 [==============================] - 1s 625us/step - loss: 0.5479 - accuracy: 0.7338
Epoch 47/200
804/804 [==============================] - 1s 678us/step - loss: 0.5480 - accuracy: 0.7348
Epoch 48/200
804/804 [==============================] - 1s 689us/step - loss: 0.5479 - accuracy: 0.7330
Epoch 49/200
804/804 [==============================] - 1s 785us/step - loss: 0.5478 - accuracy: 0.7339
Epoch 50/200
804/804 [==============================] - 1s 794us/step - loss: 0.5472 - accuracy: 0.7341
Epoch 51/200
804/804 [==============================] - 1s 762us/step - loss: 0.5476 - accuracy: 0.7335
Epoch 52/200
804/804 [==============================] - 1s 700us/step - loss: 0.5473 - accuracy: 0.7335
Epoch 53/200
804/804 [==============================] - 1s 697us/step - loss: 0.5471 - accuracy: 0.7337
Epoch 54/200
804/804 [==============================] - 1s 702us/step - loss: 0.5471 - accuracy: 0.7343
Epoch 55/200
804/804 [==============================] - 1s 696us/step - loss: 0.5471 - accuracy: 0.7344
Epoch 56/200
804/804 [==============================] - 1s 700us/step - loss: 0.5475 - accuracy: 0.7337
Epoch 57/200
804/804 [==============================] - 1s 694us/step - loss: 0.5474 - accuracy: 0.7336
Epoch 58/200
804/804 [==============================] - 1s 700us/step - loss: 0.5471 - accuracy: 0.7337
Epoch 59/200
804/804 [==============================] - 1s 709us/step - loss: 0.5471 - accuracy: 0.7336
Epoch 60/200
804/804 [==============================] - 1s 699us/step - loss: 0.5471 - accuracy: 0.7343
Epoch 61/200
804/804 [==============================] - 1s 705us/step - loss: 0.5469 - accuracy: 0.7343
Epoch 62/200
804/804 [==============================] - 1s 709us/step - loss: 0.5469 - accuracy: 0.7340
Epoch 63/200
804/804 [==============================] - 1s 708us/step - loss: 0.5468 - accuracy: 0.7344
Epoch 64/200
804/804 [==============================] - 1s 698us/step - loss: 0.5468 - accuracy: 0.7344
Epoch 65/200
804/804 [==============================] - 1s 782us/step - loss: 0.5469 - accuracy: 0.7334
Epoch 66/200
804/804 [==============================] - 1s 815us/step - loss: 0.5466 - accuracy: 0.7348
Epoch 67/200
804/804 [==============================] - 1s 821us/step - loss: 0.5466 - accuracy: 0.7346
Epoch 68/200
804/804 [==============================] - 1s 820us/step - loss: 0.5466 - accuracy: 0.7334
Epoch 69/200
804/804 [==============================] - 1s 790us/step - loss: 0.5464 - accuracy: 0.7343
Epoch 70/200
804/804 [==============================] - 1s 646us/step - loss: 0.5464 - accuracy: 0.7355
Epoch 71/200
804/804 [==============================] - 1s 694us/step - loss: 0.5465 - accuracy: 0.7343
Epoch 72/200
804/804 [==============================] - 1s 694us/step - loss: 0.5463 - accuracy: 0.7345
Epoch 73/200
804/804 [==============================] - 1s 693us/step - loss: 0.5463 - accuracy: 0.7341
Epoch 74/200
804/804 [==============================] - 1s 699us/step - loss: 0.5462 - accuracy: 0.7338
Epoch 75/200
804/804 [==============================] - 1s 845us/step - loss: 0.5464 - accuracy: 0.7341
Epoch 76/200
804/804 [==============================] - 1s 631us/step - loss: 0.5462 - accuracy: 0.7349
Epoch 77/200
804/804 [==============================] - 1s 628us/step - loss: 0.5463 - accuracy: 0.7335
Epoch 78/200
804/804 [==============================] - 1s 674us/step - loss: 0.5462 - accuracy: 0.7339
Epoch 79/200

804/804 [==============================] - 1s 623us/step - loss: 0.5461 - accuracy: 0.7340
Epoch 80/200
804/804 [==============================] - 1s 622us/step - loss: 0.5460 - accuracy: 0.7350
Epoch 81/200
804/804 [==============================] - 1s 630us/step - loss: 0.5461 - accuracy: 0.7353
Epoch 82/200
804/804 [==============================] - 1s 688us/step - loss: 0.5458 - accuracy: 0.7354
Epoch 83/200
804/804 [==============================] - 1s 684us/step - loss: 0.5458 - accuracy: 0.7348
Epoch 84/200
804/804 [==============================] - 1s 686us/step - loss: 0.5455 - accuracy: 0.7345
Epoch 85/200
804/804 [==============================] - 1s 648us/step - loss: 0.5459 - accuracy: 0.7340
Epoch 86/200
804/804 [==============================] - 1s 703us/step - loss: 0.5457 - accuracy: 0.7350
Epoch 87/200
804/804 [==============================] - 1s 692us/step - loss: 0.5456 - accuracy: 0.7352
Epoch 88/200
804/804 [==============================] - 1s 693us/step - loss: 0.5453 - accuracy: 0.7351
Epoch 89/200
804/804 [==============================] - 1s 693us/step - loss: 0.5453 - accuracy: 0.7344
Epoch 90/200
804/804 [==============================] - 1s 686us/step - loss: 0.5453 - accuracy: 0.7344
Epoch 91/200
804/804 [==============================] - 1s 696us/step - loss: 0.5458 - accuracy: 0.7345
Epoch 92/200
804/804 [==============================] - 1s 697us/step - loss: 0.5455 - accuracy: 0.7355
Epoch 93/200
804/804 [==============================] - 1s 710us/step - loss: 0.5455 - accuracy: 0.7350
Epoch 94/200
804/804 [==============================] - 1s 752us/step - loss: 0.5453 - accuracy: 0.7345
Epoch 95/200
804/804 [==============================] - 1s 756us/step - loss: 0.5454 - accuracy: 0.7348
Epoch 96/200
804/804 [==============================] - 1s 752us/step - loss: 0.5452 - accuracy: 0.7350
Epoch 97/200
804/804 [==============================] - 1s 842us/step - loss: 0.5453 - accuracy: 0.7332
Epoch 98/200
804/804 [==============================] - 1s 832us/step - loss: 0.5454 - accuracy: 0.7349
Epoch 99/200
804/804 [==============================] - 1s 741us/step - loss: 0.5451 - accuracy: 0.7353
Epoch 100/200
804/804 [==============================] - 1s 745us/step - loss: 0.5451 - accuracy: 0.7359
Epoch 101/200
804/804 [==============================] - 1s 733us/step - loss: 0.5451 - accuracy: 0.7348
Epoch 102/200
804/804 [==============================] - 1s 753us/step - loss: 0.5455 - accuracy: 0.7355
Epoch 103/200
804/804 [==============================] - 1s 761us/step - loss: 0.5453 - accuracy: 0.7355
Epoch 104/200
804/804 [==============================] - 1s 745us/step - loss: 0.5447 - accuracy: 0.7361
Epoch 105/200
804/804 [==============================] - 1s 743us/step - loss: 0.5453 - accuracy: 0.7353
Epoch 106/200
804/804 [==============================] - 1s 684us/step - loss: 0.5455 - accuracy: 0.7348
Epoch 107/200
804/804 [==============================] - 1s 679us/step - loss: 0.5454 - accuracy: 0.7356
Epoch 108/200
804/804 [==============================] - 1s 720us/step - loss: 0.5449 - accuracy: 0.73620s - loss: 0.5446 -
Epoch 109/200
804/804 [==============================] - 1s 729us/step - loss: 0.5451 - accuracy: 0.7351
Epoch 110/200
804/804 [==============================] - 1s 698us/step - loss: 0.5451 - accuracy: 0.7353
Epoch 111/200
804/804 [==============================] - 1s 703us/step - loss: 0.5451 - accuracy: 0.7351
Epoch 112/200
804/804 [==============================] - 1s 722us/step - loss: 0.5451 - accuracy: 0.7343
Epoch 113/200
804/804 [==============================] - 1s 763us/step - loss: 0.5450 - accuracy: 0.7349
Epoch 114/200
804/804 [==============================] - 1s 693us/step - loss: 0.5449 - accuracy: 0.7355
Epoch 115/200
804/804 [==============================] - 1s 696us/step - loss: 0.5450 - accuracy: 0.7345
Epoch 116/200
804/804 [==============================] - 1s 694us/step - loss: 0.5445 - accuracy: 0.7353
Epoch 117/200
804/804 [==============================] - 1s 694us/step - loss: 0.5448 - accuracy: 0.7357
Epoch 118/200
804/804 [==============================] - 1s 692us/step - loss: 0.5448 - accuracy: 0.7350
Epoch 119/200
804/804 [==============================] - 1s 691us/step - loss: 0.5449 - accuracy: 0.7350
Epoch 120/200
804/804 [==============================] - 1s 689us/step - loss: 0.5449 - accuracy: 0.7345
Epoch 121/200
804/804 [==============================] - 1s 687us/step - loss: 0.5450 - accuracy: 0.7345
Epoch 122/200
804/804 [==============================] - 1s 694us/step - loss: 0.5449 - accuracy: 0.7354
Epoch 123/200
804/804 [==============================] - 1s 688us/step - loss: 0.5449 - accuracy: 0.7349
Epoch 124/200
804/804 [==============================] - 1s 693us/step - loss: 0.5447 - accuracy: 0.7352
Epoch 125/200
804/804 [==============================] - 1s 660us/step - loss: 0.5448 - accuracy: 0.7343
Epoch 126/200
804/804 [==============================] - 1s 635us/step - loss: 0.5449 - accuracy: 0.7343
Epoch 127/200
804/804 [==============================] - 1s 678us/step - loss: 0.5447 - accuracy: 0.7345
Epoch 128/200
804/804 [==============================] - 1s 653us/step - loss: 0.5445 - accuracy: 0.7355
Epoch 129/200
804/804 [==============================] - 1s 646us/step - loss: 0.5448 - accuracy: 0.7358
Epoch 130/200
804/804 [==============================] - 1s 687us/step - loss: 0.5447 - accuracy: 0.7351
Epoch 131/200
804/804 [==============================] - 1s 697us/step - loss: 0.5449 - accuracy: 0.7342
Epoch 132/200
804/804 [==============================] - 1s 693us/step - loss: 0.5445 - accuracy: 0.7359
Epoch 133/200
804/804 [==============================] - 1s 699us/step - loss: 0.5447 - accuracy: 0.7345
Epoch 134/200
804/804 [==============================] - 1s 693us/step - loss: 0.5445 - accuracy: 0.7354
Epoch 135/200
804/804 [==============================] - 1s 693us/step - loss: 0.5447 - accuracy: 0.7357
Epoch 136/200
804/804 [==============================] - 1s 682us/step - loss: 0.5447 - accuracy: 0.7354
Epoch 137/200
804/804 [==============================] - 1s 686us/step - loss: 0.5444 - accuracy: 0.7368
Epoch 138/200
804/804 [==============================] - 1s 698us/step - loss: 0.5443 - accuracy: 0.7348
Epoch 139/200
804/804 [==============================] - 1s 692us/step - loss: 0.5443 - accuracy: 0.7363
Epoch 140/200
804/804 [==============================] - 1s 684us/step - loss: 0.5445 - accuracy: 0.7355
Epoch 141/200
804/804 [==============================] - 1s 688us/step - loss: 0.5444 - accuracy: 0.7351
Epoch 142/200
804/804 [==============================] - 1s 689us/step - loss: 0.5442 - accuracy: 0.7355
Epoch 143/200
804/804 [==============================] - 1s 692us/step - loss: 0.5442 - accuracy: 0.7357
Epoch 144/200
804/804 [==============================] - 1s 692us/step - loss: 0.5444 - accuracy: 0.7332
Epoch 145/200
804/804 [==============================] - 1s 692us/step - loss: 0.5443 - accuracy: 0.7362
Epoch 146/200
804/804 [==============================] - 1s 688us/step - loss: 0.5441 - accuracy: 0.7352
Epoch 147/200
804/804 [==============================] - 1s 697us/step - loss: 0.5445 - accuracy: 0.7355
Epoch 148/200
804/804 [==============================] - 1s 692us/step - loss: 0.5445 - accuracy: 0.7354
Epoch 149/200
804/804 [==============================] - 1s 694us/step - loss: 0.5442 - accuracy: 0.7354
Epoch 150/200
804/804 [==============================] - 1s 699us/step - loss: 0.5442 - accuracy: 0.7350
Epoch 151/200
804/804 [==============================] - 1s 679us/step - loss: 0.5444 - accuracy: 0.7356
Epoch 152/200
804/804 [==============================] - 1s 688us/step - loss: 0.5440 - accuracy: 0.7359
Epoch 153/200
804/804 [==============================] - 1s 689us/step - loss: 0.5442 - accuracy: 0.7354
Epoch 154/200
804/804 [==============================] - 1s 689us/step - loss: 0.5442 - accuracy: 0.7362
Epoch 155/200
804/804 [==============================] - 1s 689us/step - loss: 0.5443 - accuracy: 0.7349
Epoch 156/200
804/804 [==============================] - 1s 652us/step - loss: 0.5442 - accuracy: 0.7356
Epoch 157/200

804/804 [==============================] - 1s 646us/step - loss: 0.5442 - accuracy: 0.7355
Epoch 158/200
804/804 [==============================] - 1s 632us/step - loss: 0.5438 - accuracy: 0.7360
Epoch 159/200
804/804 [==============================] - 1s 686us/step - loss: 0.5442 - accuracy: 0.7353
Epoch 160/200
804/804 [==============================] - 1s 683us/step - loss: 0.5439 - accuracy: 0.7355
Epoch 161/200
804/804 [==============================] - 1s 682us/step - loss: 0.5440 - accuracy: 0.7367
Epoch 162/200
804/804 [==============================] - 1s 683us/step - loss: 0.5441 - accuracy: 0.7357
Epoch 163/200
804/804 [==============================] - 1s 683us/step - loss: 0.5438 - accuracy: 0.7359
Epoch 164/200
804/804 [==============================] - 1s 688us/step - loss: 0.5439 - accuracy: 0.7356
Epoch 165/200
804/804 [==============================] - 1s 687us/step - loss: 0.5438 - accuracy: 0.7361
Epoch 166/200
804/804 [==============================] - 1s 686us/step - loss: 0.5440 - accuracy: 0.7360
Epoch 167/200
804/804 [==============================] - 1s 683us/step - loss: 0.5440 - accuracy: 0.7358
Epoch 168/200
804/804 [==============================] - 1s 689us/step - loss: 0.5437 - accuracy: 0.7358
Epoch 169/200
804/804 [==============================] - 1s 688us/step - loss: 0.5438 - accuracy: 0.7360
Epoch 170/200
804/804 [==============================] - 1s 684us/step - loss: 0.5438 - accuracy: 0.7360
Epoch 171/200
804/804 [==============================] - 1s 684us/step - loss: 0.5440 - accuracy: 0.7365
Epoch 172/200
804/804 [==============================] - 1s 684us/step - loss: 0.5438 - accuracy: 0.7357
Epoch 173/200
804/804 [==============================] - 1s 684us/step - loss: 0.5440 - accuracy: 0.7355
Epoch 174/200
804/804 [==============================] - 1s 692us/step - loss: 0.5440 - accuracy: 0.7360
Epoch 175/200
804/804 [==============================] - 1s 679us/step - loss: 0.5440 - accuracy: 0.7358
Epoch 176/200
804/804 [==============================] - 1s 681us/step - loss: 0.5437 - accuracy: 0.7358
Epoch 177/200
804/804 [==============================] - 1s 687us/step - loss: 0.5438 - accuracy: 0.7358
Epoch 178/200
804/804 [==============================] - 1s 697us/step - loss: 0.5434 - accuracy: 0.7356
Epoch 179/200
804/804 [==============================] - 1s 692us/step - loss: 0.5438 - accuracy: 0.7350
Epoch 180/200
804/804 [==============================] - 1s 681us/step - loss: 0.5437 - accuracy: 0.7354
Epoch 181/200
804/804 [==============================] - 1s 686us/step - loss: 0.5438 - accuracy: 0.7360
Epoch 182/200
804/804 [==============================] - 1s 694us/step - loss: 0.5436 - accuracy: 0.7358
Epoch 183/200
804/804 [==============================] - 1s 687us/step - loss: 0.5438 - accuracy: 0.7357
Epoch 184/200
804/804 [==============================] - 1s 687us/step - loss: 0.5433 - accuracy: 0.7347
Epoch 185/200
804/804 [==============================] - 1s 684us/step - loss: 0.5438 - accuracy: 0.7349
Epoch 186/200
804/804 [==============================] - 1s 682us/step - loss: 0.5436 - accuracy: 0.7364
Epoch 187/200
804/804 [==============================] - 1s 684us/step - loss: 0.5433 - accuracy: 0.7365
Epoch 188/200
804/804 [==============================] - 1s 681us/step - loss: 0.5435 - accuracy: 0.7355
Epoch 189/200
804/804 [==============================] - 1s 686us/step - loss: 0.5437 - accuracy: 0.7356
Epoch 190/200
804/804 [==============================] - 1s 688us/step - loss: 0.5438 - accuracy: 0.7361
Epoch 191/200
804/804 [==============================] - 1s 678us/step - loss: 0.5440 - accuracy: 0.7359
Epoch 192/200
804/804 [==============================] - 0s 619us/step - loss: 0.5433 - accuracy: 0.7353
Epoch 193/200
804/804 [==============================] - 0s 616us/step - loss: 0.5435 - accuracy: 0.7362
Epoch 194/200
804/804 [==============================] - 0s 621us/step - loss: 0.5437 - accuracy: 0.7361
Epoch 195/200
804/804 [==============================] - 0s 621us/step - loss: 0.5436 - accuracy: 0.7354
Epoch 196/200
804/804 [==============================] - 1s 713us/step - loss: 0.5434 - accuracy: 0.7357
Epoch 197/200
804/804 [==============================] - 1s 736us/step - loss: 0.5433 - accuracy: 0.7362
Epoch 198/200
804/804 [==============================] - 1s 737us/step - loss: 0.5432 - accuracy: 0.7362
Epoch 199/200
804/804 [==============================] - 1s 745us/step - loss: 0.5432 - accuracy: 0.7357
Epoch 200/200
804/804 [==============================] - 1s 732us/step - loss: 0.5438 - accuracy: 0.7354

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(xtest_scaled,ytest,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5574 - accuracy: 0.7231 - 227ms/epoch - 845us/step
Loss: 0.5573951601982117, Accuracy: 0.7231487035751343